/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaz;
import Modelos.Reserva;
import ModelosDAO.ReservaDAO;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author nivek
 */
public class RESERVA extends javax.swing.JInternalFrame {

    
    
ReservaDAO dao = new ReservaDAO();
DefaultTableModel modelo = new DefaultTableModel();
    
    /**
     * Creates new form RESERVA
     */
    public RESERVA() {
        initComponents();
         listar();
    }
    
    private void guardar() {
    Reserva r = new Reserva();

    r.setHuesped_id(Integer.parseInt(txtHuespedId.getText()));
    r.setEmpleado_id(Integer.parseInt(txtEmpleadoId.getText()));
    r.setHabitacion_id(Integer.parseInt(txtHabitacionId.getText()));
    r.setFecha_entrada(txtFechaEntrada.getText());
    r.setFecha_salida(txtFechaSalida.getText());
    r.setPrecio_total(Double.parseDouble(txtPrecio.getText()));
    r.setEstado(cbEstado.getSelectedItem().toString());
   
    r.setNumero_adultos(Integer.parseInt(txtAdultos.getText()));
    r.setNumero_ninos(Integer.parseInt(txtNinos.getText()));
    r.setObservaciones(txtObservaciones.getText());

    if (dao.insertar(r)) {
        listar();
        limpiar();
    }
}
    
    
    private void actualizar() {
    Reserva r = new Reserva();

    r.setReserva_id(Integer.parseInt(txtId.getText()));
    r.setHuesped_id(Integer.parseInt(txtHuespedId.getText()));
    r.setEmpleado_id(Integer.parseInt(txtEmpleadoId.getText()));
    r.setHabitacion_id(Integer.parseInt(txtHabitacionId.getText()));
    r.setFecha_entrada(txtFechaEntrada.getText());
    r.setFecha_salida(txtFechaSalida.getText());
    r.setPrecio_total(Double.parseDouble(txtPrecio.getText()));
    r.setEstado(cbEstado.getSelectedItem().toString());
   
    r.setNumero_adultos(Integer.parseInt(txtAdultos.getText()));
    r.setNumero_ninos(Integer.parseInt(txtNinos.getText()));
    r.setObservaciones(txtObservaciones.getText());

    if (dao.actualizar(r)) {
        listar();
        limpiar();
    }
}
    
    private void eliminar() {
    int id = Integer.parseInt(txtId.getText());

    if (dao.eliminar(id)) {
        listar();
        limpiar();
    }
}
    
   private void tablaClick() {
    int fila = tablaReservas.getSelectedRow();

    if (fila == -1) return;

    txtId.setText(modelo.getValueAt(fila, 0).toString());
    txtHuespedId.setText(modelo.getValueAt(fila, 1).toString());
    txtEmpleadoId.setText(modelo.getValueAt(fila, 2).toString());
    txtHabitacionId.setText(modelo.getValueAt(fila, 3).toString());
    txtFechaEntrada.setText(modelo.getValueAt(fila, 4).toString());
    txtFechaSalida.setText(modelo.getValueAt(fila, 5).toString());
    txtPrecio.setText(modelo.getValueAt(fila, 6).toString());
    cbEstado.setSelectedItem(modelo.getValueAt(fila, 7).toString());
}
    
    private void limpiar() {
    txtId.setText("");
    txtHuespedId.setText("");
    txtEmpleadoId.setText("");
    txtHabitacionId.setText("");
    txtFechaEntrada.setText("");
    txtFechaSalida.setText("");
    txtPrecio.setText("");
    txtAdultos.setText("");
    txtNinos.setText("");
    txtObservaciones.setText("");
}
    public void listar() {
    modelo.setRowCount(0);

    String[] columnas = {
    "ID", "Huesped", "Empleado", "Habitación",
    "Entrada", "Salida", "Precio", "Estado",
    "Adultos", "Niños"
};
    modelo.setColumnIdentifiers(columnas);

    for (Reserva r : dao.listar()) {
        modelo.addRow(new Object[]{
            r.getReserva_id(),
            r.getHuesped_id(),
            r.getEmpleado_id(),
            r.getHabitacion_id(),
            r.getFecha_entrada(),
            r.getFecha_salida(),
            r.getPrecio_total(),
            r.getEstado()
        });
    }

    tablaReservas.setModel(modelo);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHuespedId = new javax.swing.JTextField();
        txtEmpleadoId = new javax.swing.JTextField();
        txtHabitacionId = new javax.swing.JTextField();
        txtFechaEntrada = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtNinos = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        txtAdultos = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReservas = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();

        txtHuespedId.setText("txtHuespedId");
        txtHuespedId.addActionListener(this::txtHuespedIdActionPerformed);

        txtEmpleadoId.setText("txtEmpleadoId");

        txtHabitacionId.setText("txtHabitacionId");
        txtHabitacionId.addActionListener(this::txtHabitacionIdActionPerformed);

        txtFechaEntrada.setText("txtFechaEntrada");
        txtFechaEntrada.addActionListener(this::txtFechaEntradaActionPerformed);

        txtFechaSalida.setText("txtFechaSalida");

        txtPrecio.setText("txtPrecio");
        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        txtNinos.setText("txtNinos");
        txtNinos.addActionListener(this::txtNinosActionPerformed);

        txtObservaciones.setText("txtObservaciones");

        txtAdultos.setText("txtAdultos");
        txtAdultos.addActionListener(this::txtAdultosActionPerformed);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Confirmada", "Cancelada" }));

        btnActualizar.setText("btnActualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("btnEliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnNuevo.setText("btnNuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnGuardar.setText("btnGuardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        tablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaReservas);

        txtId.setEditable(false);
        txtId.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmpleadoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHuespedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHabitacionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHuespedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmpleadoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHabitacionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo))
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHuespedIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHuespedIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHuespedIdActionPerformed

    private void txtHabitacionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHabitacionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHabitacionIdActionPerformed

    private void txtFechaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEntradaActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNinosActionPerformed

    private void txtAdultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdultosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdultosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
guardar();  
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
limpiar();        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tablaReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaReservasMouseClicked
      tablaClick();
    }//GEN-LAST:event_tablaReservasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReservas;
    private javax.swing.JTextField txtAdultos;
    private javax.swing.JTextField txtEmpleadoId;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtHabitacionId;
    private javax.swing.JTextField txtHuespedId;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNinos;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
